apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  replicas: 1               
  selector:               
    matchLabels:          
      app: counter
  template:
    metadata:
      name: counter-pod                
      labels:
        app: counter
    spec:
      containers:                       
        - name: count
          image: busybox
          args: [/bin/sh, -c,
                  'i=0; while true; do echo "$i: $(date): hello from counter"; i=$((i+1)); sleep 1; done']