backend:
  type: es
  es:
    host: <ip>
    port: 9200
    # Elastic Index Name
    index: k8s_log
    type: flb_type
    logstash_prefix: k8s_log
    replace_dots: "On"
    time_key: "@timestamp"

# Need for custom docker directory
extraVolumeMounts:
  - name: customdocker
    mountPath: /data/docker/containers
    readOnly: true

extraVolumes:
  - name: customdocker
    hostPath:
      path: /data/docker/containers

parsers:
  enabled: false
